# Generated by Django 4.2.17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_model', models.CharField(choices=[('gpt-4o', 'GPT-4o')], default='gpt-4o', max_length=50, verbose_name='Modèle IA actif')),
            ],
            options={
                'verbose_name': "Configuration de l'application",
                'verbose_name_plural': "Configuration de l'application",
            },
        ),
    ]