# Generated by Django 4.2.24 on 2026-02-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appconfig',
            name='active_model',
            field=models.CharField(choices=[('gpt-4o', 'GPT-4o'), ('gemini-1.5-flash', 'Gemini 1.5 Flash'), ('gemini-2.0-flash', 'Gemini 2.0 Flash')], default='gpt-4o', max_length=50, verbose_name='Modèle IA actif'),
        ),
    ]
