# Generated by Django 4.2.24 on 2025-10-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="question_context",
            field=models.TextField(
                blank=True, help_text="La question de l'exercice extraite par l'IA."
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="solution_context",
            field=models.TextField(
                blank=True, help_text="La solution de l'exercice extraite par l'IA."
            ),
        ),
    ]
