# Generated by Django 4.2.24 on 2025-10-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutor", "0002_chatsession_question_context_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="teacher_notes",
            field=models.TextField(
                blank=True, help_text="Notes privées du professeur sur cette session."
            ),
        ),
    ]
