# Generated by Django 4.2.24 on 2025-10-08 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tutor", "0003_chatsession_teacher_notes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatsession",
            options={},
        ),
        migrations.RemoveField(
            model_name="chatsession",
            name="teacher_notes",
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="question_context",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="solution_context",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
