# Generated by Django 4.2.24 on 2025-10-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutor", "0004_alter_chatsession_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="summary_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
