# Generated by Django 4.2.24 on 2025-10-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutor", "0005_chatsession_summary_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="whiteboard_state",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
