# Generated by Django 4.2.17 on 2025-10-12 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutor", "0006_chatsession_whiteboard_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="teacher_diagnostic_notes",
            field=models.TextField(
                blank=True, help_text="Analyse qualitative de l'enseignant."
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="teacher_error_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("calcul", "Erreur de calcul"),
                    ("substitution", "Erreur de substitution"),
                    ("procedure", "Erreur de procédure"),
                    ("conceptuelle", "Erreur conceptuelle"),
                    ("autre", "Autre"),
                ],
                help_text="Type d'erreur principal identifié par l'enseignant.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="summary_data",
            field=models.JSONField(
                blank=True,
                help_text="Résumé et analyse d'erreur générés par l'IA.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="whiteboard_state",
            field=models.JSONField(
                blank=True,
                help_text="Dernier état sauvegardé du tableau blanc.",
                null=True,
            ),
        ),
    ]
