# Generated by Django 4.2.17 on 2025-10-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutor", "0007_chatsession_teacher_diagnostic_notes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatsession",
            name="teacher_diagnostic_notes",
        ),
        migrations.RemoveField(
            model_name="chatsession",
            name="teacher_error_type",
        ),
        migrations.AddField(
            model_name="chatsession",
            name="teacher_analysis",
            field=models.JSONField(
                blank=True,
                help_text="Analyse structurée de l'enseignant (nombre d'erreurs, notes).",
                null=True,
            ),
        ),
    ]
