# Generated by Django 4.2.24 on 2026-02-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutor", "0008_remove_chatsession_teacher_diagnostic_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatsession",
            name="summary_data",
            field=models.JSONField(
                blank=True,
                help_text="Summary and error analysis generated by the AI.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="teacher_analysis",
            field=models.JSONField(
                blank=True,
                help_text="Structured analysis from the teacher. Contains 'error_analysis', 'notes', 'divergence_analysis', 'remediation_strategy', 'ai_influence_rating'.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="whiteboard_state",
            field=models.JSONField(
                blank=True, help_text="Last saved state of the whiteboard.", null=True
            ),
        ),
    ]
