# Generated by Django 4.2.24 on 2025-10-10 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Ex: Groupes pour le projet 'Volcans'", max_length=255
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        help_text="La structure des groupes, ex: [['Alice', 'Bob'], ['Charlie']]"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "teacher_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_configurations",
                        to="auth.group",
                    ),
                ),
            ],
        ),
    ]
