# Generated by Django 4.2.24 on 2026-02-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupconfiguration",
            name="configuration",
            field=models.JSONField(
                help_text="The group structure, e.g., [['Alice', 'Bob'], ['Charlie']]"
            ),
        ),
        migrations.AlterField(
            model_name="groupconfiguration",
            name="name",
            field=models.CharField(
                help_text="E.g., Groups for the 'Volcanoes' project", max_length=255
            ),
        ),
    ]
