# Generated by Django 4.2.24 on 2026-02-18 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_alter_groupconfiguration_configuration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confidence', models.IntegerField(verbose_name='Confiance en soi')),
                ('clarity', models.IntegerField(verbose_name='Clarté du cours')),
                ('ai_helpfulness', models.IntegerField(verbose_name="Aide de l'IA")),
                ('motivation', models.IntegerField(verbose_name='Motivation')),
                ('pace', models.IntegerField(verbose_name='Rythme de travail')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Commentaires libres')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
