# Generated by Django 4.2.24 on 2026-02-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_surveyresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresponse',
            name='ai_helpfulness',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='clarity',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='motivation',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='pace',
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='competence_capability',
            field=models.IntegerField(default=3, verbose_name='Capacité résolution'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='competence_confidence',
            field=models.IntegerField(default=3, verbose_name='Confiance en soi'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='competence_new_ways',
            field=models.IntegerField(default=3, verbose_name='Nouvelles façons de penser'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='competence_preference',
            field=models.IntegerField(default=3, verbose_name='Préférence IA'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='ease_asking',
            field=models.IntegerField(default=3, verbose_name='Facilité questions'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='ease_knowing',
            field=models.IntegerField(default=3, verbose_name='Savoir quoi demander'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='ease_reformulation',
            field=models.IntegerField(default=3, verbose_name='Reformulation nécessaire'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='ease_understanding',
            field=models.IntegerField(default=3, verbose_name="Compréhension par l'IA"),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='open_confusion',
            field=models.TextField(blank=True, null=True, verbose_name='Moments de confusion'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='open_difficulty',
            field=models.TextField(blank=True, null=True, verbose_name='Difficulté du prompting'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='relation_interest',
            field=models.IntegerField(default=3, verbose_name='Intérêt cours'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='relation_trust',
            field=models.IntegerField(default=3, verbose_name='Confiance conseils'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='relation_tutor',
            field=models.IntegerField(default=3, verbose_name='Posture tuteur'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='utility_correction',
            field=models.IntegerField(default=3, verbose_name='Correction autonome'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='utility_errors',
            field=models.IntegerField(default=3, verbose_name='Aide erreurs'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='utility_hints',
            field=models.IntegerField(default=3, verbose_name='Indices utiles'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='utility_understanding',
            field=models.IntegerField(default=3, verbose_name='Compréhension chapitre'),
        ),
    ]
