# tutor/models.py

from django.db import models
from django.conf import settings

# Make sure to import your Document model
from documents.models import Document 

class ChatSession(models.Model):
    student = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    document = models.ForeignKey(Document, on_delete=models.SET_NULL, null=True, blank=True)
    question_context = models.TextField()
    solution_context = models.TextField()
    start_time = models.DateTimeField(auto_now_add=True)
    end_time = models.DateTimeField(null=True, blank=True)
    summary_data = models.JSONField(null=True, blank=True, help_text="Summary and error analysis generated by the AI.")
    whiteboard_state = models.JSONField(null=True, blank=True, help_text="Last saved state of the whiteboard.")

    # New fields for teacher diagnosis
    TEACHER_ERROR_CHOICES = [
        ('calcul', 'Calculation Error'),
        ('substitution', 'Substitution Error'),
        ('procedure', 'Procedural Error'),
        ('conceptuelle', 'Conceptual Error'),
        ('autre', 'Other'),
    ]
    teacher_analysis = models.JSONField(null=True, blank=True, help_text="Structured analysis from the teacher. Contains 'error_analysis', 'notes', 'divergence_analysis', 'remediation_strategy', 'ai_influence_rating'.")

    AI_INFLUENCE_CHOICES = [
        (1, 'Not at all'),
        (2, 'A little'),
        (3, 'Moderately'),
        (4, 'A lot'),
    ]

    def __str__(self):
        return f"Session for {self.student.username} on {self.start_time.strftime('%Y-%m-%d')}"

class ChatMessage(models.Model):
    session = models.ForeignKey(ChatSession, related_name='messages', on_delete=models.CASCADE)
    role = models.CharField(max_length=10, choices=[('user', 'User'), ('assistant', 'Assistant')])
    
    # Using JSONField to store complex data (text + image)
    content = models.JSONField() 
    
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.role} at {self.timestamp.strftime('%H:%M')}"