# Generated by Django 4.2.17 on 2025-10-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_populate_curriculum_structure"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["order", "name"],
                "verbose_name": "Catégorie",
                "verbose_name_plural": "Catégories",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="order",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Ordre d'affichage"
            ),
        ),
    ]
